# Generated by Django 3.2.9 on 2021-12-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=None)),
                ('category', models.CharField(choices=[('class room', 'class room'), ('competitions', 'competitions')], max_length=50)),
            ],
        ),
    ]
