# Generated by Django 3.2.9 on 2021-12-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('long_description', models.TextField(null=True)),
                ('short_description', models.TextField(null=True)),
                ('fees', models.FloatField(null=True)),
                ('student_number', models.IntegerField(null=True)),
                ('min_age', models.IntegerField(null=True)),
                ('max_age', models.IntegerField(null=True)),
                ('cover_image', models.ImageField(null=True, upload_to=None)),
                ('list_image', models.ImageField(null=True, upload_to=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_of_event', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('long_description', models.TextField(null=True)),
                ('short_description', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('min_age', models.IntegerField(null=True)),
                ('max_age', models.IntegerField(null=True)),
                ('cover_image', models.ImageField(null=True, upload_to=None)),
                ('list_image', models.ImageField(null=True, upload_to=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('specialization', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('quotes', models.TextField(null=True)),
                ('facebook', models.CharField(max_length=50, null=True)),
                ('twitter', models.CharField(max_length=50, null=True)),
                ('google', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
