# Generated by Django 3.2.6 on 2021-08-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willyWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
