# Generated by Django 3.2.6 on 2021-08-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('willyWeb', '0002_gallery_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='likes',
        ),
    ]
