# Generated by Django 3.2.6 on 2021-09-05 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('willyWeb', '0002_auto_20210905_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration_Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('mail', models.EmailField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('denied', 'denied')], default='pending', max_length=50)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='willyWeb.competition')),
            ],
        ),
    ]
