# Generated by Django 3.2.6 on 2021-08-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willyWeb', '0003_remove_gallery_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('long_description', models.TextField(null=True)),
                ('short_description', models.TextField(null=True)),
                ('fees', models.FloatField(null=True)),
                ('student_number', models.IntegerField(null=True)),
                ('min_age', models.IntegerField(null=True)),
                ('max_age', models.IntegerField(null=True)),
                ('cover_image', models.ImageField(null=True, upload_to=None)),
                ('list_image', models.ImageField(null=True, upload_to=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_of_event', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50)),
            ],
        ),
    ]
